name: Auto merge from default branch
on:
  push:
    branches:
      - main
jobs:
  auto-merge-from-default:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PR_FILTER: 'labelled'
          PR_LABELS: 'auto-merge-from-default'
          MERGE_MSG: 'Merge branch "${{ github.ref_name }}" into this branch.'
